// Code generated by Kitex v0.3.4. DO NOT EDIT.

package mapservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"word-count/kitex_gen/mapdemo"
)

func serviceInfo() *kitex.ServiceInfo {
	return mapServiceServiceInfo
}

var mapServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "MapService"
	handlerType := (*mapdemo.MapService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateMap": kitex.NewMethodInfo(createMapHandler, newMapServiceCreateMapArgs, newMapServiceCreateMapResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "mapdemo",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.4",
		Extra:           extra,
	}
	return svcInfo
}

func createMapHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*mapdemo.MapServiceCreateMapArgs)
	realResult := result.(*mapdemo.MapServiceCreateMapResult)
	success, err := handler.(mapdemo.MapService).CreateMap(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMapServiceCreateMapArgs() interface{} {
	return mapdemo.NewMapServiceCreateMapArgs()
}

func newMapServiceCreateMapResult() interface{} {
	return mapdemo.NewMapServiceCreateMapResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateMap(ctx context.Context, req *mapdemo.CreateMapRequest) (r *mapdemo.CreateMapResponse, err error) {
	var _args mapdemo.MapServiceCreateMapArgs
	_args.Req = req
	var _result mapdemo.MapServiceCreateMapResult
	if err = p.c.Call(ctx, "CreateMap", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
