// Code generated by Kitex v0.3.4. DO NOT EDIT.
package keybyservice

import (
	"github.com/cloudwego/kitex/server"
	"word-count/kitex_gen/keybydemo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler keybydemo.KeybyService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
