// Code generated by Kitex v0.3.4. DO NOT EDIT.

package sinkservice

import (
	"github.com/cloudwego/kitex/server"
	"word-count/cmd/sink/kitex_gen/sinkdemo"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler sinkdemo.SinkService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
